org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
java_version=21

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge Config
neo_version=21.1.250
loader_version_range=[1,)

loader=neoforge

mod_id=machinemetrics
mod_name=Machine Metrics
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.alikuxac.machinemetrics

